### ISSUE TITLE
Insta Cena site linked is comprimised

### ISSUE THREAD

**Issue by alex-r-redfern** [Roystbeef/Cenafy#4]
Hi There,
The insta cena domain appears to now be serving malware. You may wish to remove the links to this.
Thanks,
Alex

**Comment by Roystbeef** [comment]
o yikes. Thanks for letting me know

**Comment by Roystbeef** [comment]
Removed from readme

**Comment by alex-r-redfern** [comment]
No worries, sad to see it go :(
